### ISSUE TITLE
Define support for CycloneDX 1.1

### ISSUE THREAD

**Issue by stevespringett** [CycloneDX/cyclonedx-cli#10]
When converting CycloneDX 1.1 XML to SPDX, I receive the following error:

```
Unhandled exception: System.InvalidOperationException: There is an error in XML document (2, 2).
 ---> System.InvalidOperationException: <bom xmlns='http://cyclonedx.org/schema/bom/1.1'> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderBom.Read29_bom()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at CycloneDX.Xml.XmlBomDeserializer.Deserialize(Stream stream)
   at CycloneDX.Xml.XmlBomDeserializer.Deserialize(String bom)
   at CycloneDX.CLI.Utils.BomDeserializer(String bom, BomFormat format)
   at CycloneDX.CLI.Program.Convert(String inputFile, String outputFile, ConvertInputFormat inputFormat, ConvertOutputFormat outputFormat)
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

If the direction of the tool is to support only CycloneDX v1.2 and higher, then I think the tool should display a message indicating that v1.1 and lower is not supported and exit -1.

If the direction of the tool is to support all CycloneDX versions, then I think we need to build out support for it - at least from the XML side of things.

**Comment by coderpatros** [comment]
Yeah, two problems here, inadequate documentation and incomplete features.

Previous versions of the spec will be supported. At first it might just be support for reading previous versions of the spec.

I'll update the README.md to indicate current state then close this issue. And create additional issues for previous version deserialization and serialization. I'd specifically like to be able to output older spec versions as it could be a great stop gap measure for vendors that haven't yet implemented support the latest spec.
