### ISSUE TITLE
OSX: Unhandled exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 

### ISSUE THREAD

**Issue by alandtse** [CycloneDX/cyclonedx-cli#109]
On macOS Catalina 10.15.7, the docker version appears to have issues with the --input-file. I downloaded the example.csv from the repo.

I tested with both a relative file name `example.csv` and an absolute path `/Users/alantse/Downloads/example.csv'. I received the same error.

run below:
```bash
Downloads % docker run cyclonedx/cyclonedx-cli convert --input-file example.csv --output-format json
Unhandled exception: System.IO.FileNotFoundException: Could not find file '/example.csv'.
File name: '/example.csv'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.AsyncStreamReader(String path, Encoding encoding)
   at System.IO.File.InternalReadAllTextAsync(String path, Encoding encoding, CancellationToken cancellationToken)
   at CycloneDX.CLI.Program.InputFileHelper(String inputFile)
   at CycloneDX.CLI.Program.Convert(String inputFile, String outputFile, InputFormat inputFormat, ConvertOutputFormat outputFormat)
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

I can confirm the file is there:
```bash
Downloads % ls example.csv && pwd && head example.csv
example.csv
/Users/alantse/Downloads
Type,MimeType,Supplier,Author,Publisher,Group,Name,Version,Scope,LicenseExpressions,LicenseNames,Copyright,Cpe,Purl,Modified,SwidTagId,SwidName,SwidVersion,SwidTagVersion,SwidPatch,SwidTextContentType,SwidTextEncoding,SwidTextContent,SwidUrl,MD5,SHA-1,SHA-256,SHA-512,BLAKE2b-256,BLAKE2b-384,BLAKE2b-512,SHA-384,SHA3-256,SHA3-384,SHA3-512,BLAKE3,Description
Application,,,Acme Super Heros,Acme Inc,com.acme,tomcat-catalina,9.0.14,required,Apache-2.0,,,,pkg:maven/com.acme/tomcat-catalina@9.0.14?packaging=jar,,,,,,,,,,,3942447fac867ae5cdb3229b658f4d48,e6b1000b94e835ffd37f4c6dcbdad43f4b48a02a,f498a8ff2dd007e29c2074f5e4b01a9a01775c3ff3aeaf6906ea503bc5791b7b,e8f33e424f3f4ed6db76a482fde1a5298970e442c531729119e37991884bdffab4f9426b7ee11fccd074eeda0634d71697d6f88a460dce0ac8d627a29f7d1282,,,,,,,,,Modified version of Apache Catalina
Library,,Example Inc.,Example Super Heros,,org.example,mylibrary,1.0.0,required,EPL-2.0 OR GPL-2.0-with-classpath-exception,,Copyright Example Inc. All rights reserved.,cpe:/a:example:myapplication:1.0.0,pkg:maven/com.example/myapplication@1.0.0?packaging=war,False,,,,,,,,,,2342c2eaf1feb9a80195dbaddf2ebaa3,68b78babe00a053f9e35ec6a2d9080f5b90122b0,708f1f53b41f11f02d12a11b1a38d2905d47b099afc71a0f1124ef8582ec7313,387b7ae16b9cae45f830671541539bf544202faae5aac544a93b7b0a04f5f846fa2f4e81ef3f1677e13aed7496408a441f5657ab6d54423e56bf6f38da124aef,,,,,,,,,
Framework,,,Example Super Heros,,com.example,myframework,1.0.0,required,,Some random license,,,pkg:maven/com.example/myframework@1.0.0?packaging=war,False,,,,,,,,,,cfcb0b64aacd2f81c1cd546543de965a,7fbeef2346c45d565c3341f037bce4e088af8a52,0384db3cec55d86a6898c489fdb75a8e75fe66b26639634983d2f3c3558493d1,854909cdb9e3ca183056837144aab6d8069b377bd66445087cc7157bf0c3f620418705dd0b83bdc2f73a508c2bdb316ca1809d75ee6972d02023a3e7dd655c79,,,,,,,,,"Example Inc, enterprise framework"
```

**Comment by alandtse** [comment]
Oops, I forgot that docker run needs to mount the file in the container.

```bash
docker run -v `pwd`:/Downloads:ro cyclonedx/cyclonedx-cli convert --input-file /Downloads/example.csv --output-format json
```
