### ISSUE TITLE
Crash when signing bom on macOS 12.3.1 and latest docker image

### ISSUE THREAD

**Issue by sycured** [CycloneDX/cyclonedx-cli#233]
OS: macOS 12.3.1 (Intel)
cyclonedx-cli version: 0.24.0
docker image: cyclonedx/cyclonedx-cli:latest (f60f7e593c84)

Step to do on the mac:
- Generate key: `cyclonedx keygen`
- Generate BOM file: `cargo cyclonedx -a --output-cdx`

To reproduce the error locally: `cyclonedx sign bom bom.cdx.xml`
To reproduce the error using docker image: `docker run --rm -v "$PWD":/shared cyclonedx/cyclonedx-cli sign bom --key-file /shared/private.key /shared/bom.cdx.xml`

Output:
```
Loading private key...
Loading XML BOM...
Generating signature...
Unhandled exception: System.Security.Cryptography.CryptographicException: Could not create hash algorithm object.
   at System.Security.Cryptography.Xml.Reference.CalculateHashValue(XmlDocument , CanonicalXmlNodeList )
   at System.Security.Cryptography.Xml.SignedXml.BuildDigestedReferences()
   at System.Security.Cryptography.Xml.SignedXml.ComputeSignature()
   at CycloneDX.Cli.Commands.Sign.SignBomCommand.SignBom(SignBomCommandOptions options)
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by dmeibusch** [comment]
Reproduced this issue with the native macOS x86 executable for 0.24.0 and back to 0.20.0.
0.19.0 signs XML sboms successfully.
It appears this has been introduced with changes between these two release (.Net upgrade, perhaps?)

**Comment by dmeibusch** [comment]
As another reference point, the `sign file` command (macOS native, 0.24.0) does work, generating a `.sig` file successfully. A different code path, different use of .Net crypto APIs. Same input key etc...
