### ISSUE TITLE
KeyNotFoundException 

### ISSUE THREAD

**Issue by Serraniel** [CycloneDX/cyclonedx-cli#327]
I´m getting an exception when calling 
`dotnet CycloneDX "path\project.csproj" -o "..\..\..\bom\aspose" -j -d -t -tfm "net48"`

My csproj file:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net48</TargetFrameworks>
    <RuntimeIdentifiers>win-x64;win-x86;AnyCPU</RuntimeIdentifiers>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>True</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
	<GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
	<AssemblyVersion>2023.1.2.8</AssemblyVersion>
	<FileVersion>2023.1.2.8</FileVersion>
	<Copyright>Some Copyright</Copyright>
	<Version>$(AssemblyVersion) $(VersionPrefix)</Version>
	<LangVersion>8</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Gurock.SmartInspect, Version=3.3.9.166, Culture=neutral, PublicKeyToken=a78b0a9303ab7a7c, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>lib\Gurock.SmartInspect.dll</HintPath>
    </Reference>
    <Reference Include="Gurock.SmartInspect.DebugTrace, Version=3.3.9.166, Culture=neutral, PublicKeyToken=a78b0a9303ab7a7c, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>lib\Gurock.SmartInspect.DebugTrace.dll</HintPath>
    </Reference>
    <Reference Include="Gurock.SmartInspect.LinqToSql, Version=3.3.9.166, Culture=neutral, PublicKeyToken=a78b0a9303ab7a7c, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>lib\Gurock.SmartInspect.LinqToSql.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Gurock.SmartInspect.DebugTrace.dll" />
    <Content Include="Gurock.SmartInspect.dll" />
    <Content Include="Gurock.SmartInspect.LinqToSql.dll" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Aspose.Cells" Version="23.6.0" />
    <PackageReference Include="Aspose.PDF" Version="23.6.0" />
    <PackageReference Include="Aspose.Slides.NET" Version="23.5.0" />
    <PackageReference Include="Aspose.Words" Version="23.6.0" />
    <PackageReference Include="System.Resources.Extensions" Version="7.0.0" />
  </ItemGroup>
</Project>
```

The full console output:
```cli
Found the following local nuget package cache locations:
    C:\Users\awesome name\.nuget\packages\

» Analyzing: fullpath\projectname.csproj
  Attempting to restore packages
  Packages restored
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Text.Json.JsonElement.GetProperty(String propertyName)
   at CycloneDX.Services.ProjectAssetsFileService.SetIsDevDependency(String packageName, String targetRuntime, JsonElement jsonContent) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Services/ProjectAssetsFileService.cs:line 113
   at CycloneDX.Services.ProjectAssetsFileService.GetNugetPackages(String projectFilePath, String projectAssetsFilePath, Boolean isTestProject, Boolean excludeDev) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Services/ProjectAssetsFileService.cs:line 63
   at CycloneDX.Services.ProjectFileService.GetProjectNugetPackagesAsync(String projectFilePath, String baseIntermediateOutputPath, Boolean excludeTestProjects, Boolean excludeDev, String framework, String runtime) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Services/ProjectFileService.cs:line 145
   at CycloneDX.Program.OnExecuteAsync(CommandLineApplication app) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 255
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at CycloneDX.Program.Main(String[] args) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 140
   at CycloneDX.Program.<Main>(String[] args)
```

**Comment by Serraniel** [comment]
Sorry, I ended up in the wrong project, it was about cyclonedx-dotnet.
