### ISSUE TITLE
Error converting on osx with 0.6

### ISSUE THREAD

**Issue by quest313** [CycloneDX/cyclonedx-cli#36]
I seem unable to convert to csv. This BOM was generated via the maven plugin as CycloneDX 1.1.

`./cyclonedx-osx-x64 convert --input-file ~/Downloads/boms/cin-bom.xml --output-file ~/Downloads/boms/cin-bom.csv --output-format csv`

`Unhandled exception: System.InvalidOperationException: There is an error in XML document (1, 2).
 ---> System.InvalidOperationException: <bom xmlns='http://cyclonedx.org/schema/bom/1.1'> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderBom.Read9_bom()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at CycloneDX.Xml.XmlBomDeserializer.Deserialize_v1_0(Stream stream)
   at CycloneDX.Xml.XmlBomDeserializer.Deserialize(Stream stream)
   at CycloneDX.Xml.XmlBomDeserializer.Deserialize(String bom)
   at CycloneDX.CLI.Utils.BomDeserializer(String bom, BomFormat format)
   at CycloneDX.CLI.Program.Convert(String inputFile, String outputFile, InputFormat inputFormat, ConvertOutputFormat outputFormat)
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()`

**Comment by coderpatros** [comment]
Hi @quest313, are you able to share the SBOM that this is happening with?

**Comment by quest313** [comment]
Sure, this is a stripped down version that gives me the same error. I also tried this on Windows and got the same issue.


[cin-bom.xml.zip](https://github.com/CycloneDX/cyclonedx-cli/files/5661704/cin-bom.xml.zip)

**Comment by coderpatros** [comment]
Thanks @quest313, looks like there is incomplete hash support in the underlying serialization library the CLI tool uses. I'll leave this issue open until it is fully resolved.

**Comment by coderpatros** [comment]
Resolved in v0.7.0, thanks for the report @quest313
