### ISSUE TITLE
Validate Command Requirement for XSD files

### ISSUE THREAD

**Issue by msymons** [CycloneDX/cyclonedx-cli#85]
Running CLI tool 0.12.0 using the validate command will result in an exception due to XSD files not being available.

For win-x86 version checking a 1.2 BOM:

```
Using schema v1.2
Unhandled exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Utilities\CycloneDX-CLI\Schemas\bom-1.2.xsd'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Schema.XmlSchemaSet.Add(String targetNamespace, String schemaUri)
   at CycloneDX.CLI.ValidateCommand.ValidateXml(Options options, String sbomContents)
   at CycloneDX.CLI.ValidateCommand.Validate(Options options)
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()

```

Placing a copy of `bom-1.2.xsd` into a `Schemas` subdirectory resulted in another Exception, this time requesting `spdx.xsd`.

Once that was provided, all seems great...

```
$ ./cyclonedx-win-x86.exe validate --input-file bom.xml
Validating XML SBOM...
Using schema v1.2
SBOM successfully validated
```

So, I am not sure whether you would want to call this a defect, per se?  Perhaps just a gap in documentaton?

**Comment by coderpatros** [comment]
Thanks for the report @msymons 

It was an issue in how the schema files were being packaged and referenced when bundling as a single file executable.

Should be resolved in v0.12.1. But I'll wait for you to confirm before closing this issue.

**Comment by msymons** [comment]
All looks good now.  I deleted the `Schemas` subdirectory where I had placed the XSD files and CLI 0.12.1 validated my BOM without problem.

**Comment by coderpatros** [comment]
Awesome, thanks @msymons
